---
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    github-actions:
      patterns:
        - "*"
      exclude-patterns:
        - "actions/*"
        - "github/*"
        - "golangci/*"
    github-owned:
      patterns:
        - "actions/*"
        - "github/*"
