name: CI
on:
  push:
    branches:
      - main
  pull_request:

# Declare default permissions as read-only
permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: npx awesome-lint
